### ISSUE TITLE
Order events based on current location of user

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/open-city-app#72]

**Comment by petterill** [comment]
Events displayed in the events component/carousel should be ranked according to how close their coordinates are to the users current geolocation, the closest events are displayed first

**Comment by Sampax** [comment]
Discussion:
  - linkedevents does not support combination queries
  - load ALL events, sort in app  based on a combination of proximity and start time
  - should be able to incorporate user preferences in the future

**Comment by Sampax** [comment]
Rename to "Things to do nearby" or something similar
